# Site settings
title: "langoft"
email: "admin@langoft.com"
description: "一个专注于web、app开发设计的具有创意性互联网团队。"

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://www.langoft.com" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings


# 社交网络
social:
  # - title: twitter
  #   url: https://twitter.com/lantoniotrento
  # - title: facebook
  #   url: https://facebook.com/lantoniotrento
  # - title: google-plus
  #   url: https://plus.google.com/+AntoniotrentoIt
  - title: phone
    url: tel:18789248450
  - title: qq
    url: tencent://message/?uin=724261350
  - title: weixin
    url: http://www.langoft.com/contact/
  - title: weibo
    url: http://weibo.com/rontom
# 联系信息，放在contact.html
address:
  - lines: 
    - 湖南省·长沙市·开福区·湘江中路一段59号
    - 联系电话：13217481656
    - 微信公众号：weixin-liangcong
    - 备案号：琼ICP备14002517号
emailone: admin@langoft.com
emailtwo: open@langoft.com
telone: +86 13217481656(主)
teltwo: +86 18789248450
qqone: 724261350
qqtwo: 623695354

    
# 成员信息，展示在about.html
members:
  - name: 罗从良
    position: 团队负责人
    text: 专业打杂的。不曾丢失的是那颗如诗般纯真的心（总爱幻想成个诗人）。幻想着开发自己编程语言，然后使用它开发自己的应用程序。kali linux爱好者。行走Full Stack developer的路上。
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:admin@langoft.com
      - title: twitter
        url: http://twitter.com/handle
  - name: 艾华
    position: web高级工程师
    text: 专注开发web应用5年以上，熟练flask、web.py、tornado、django、plone等python架构，深刻理解php语言，开发过自己的php内容管理系统，对目前流行的nodejs等技术有着自己的见解。
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: 谢熙欣
    position: 专业设计师
    text: 喜欢画画，科班出生。站在用户角度思考设计产品，精通操作Photoshop，Illustrator、sketch等设计软件。对产品有着自己独特的创意。喜欢富有创意性的产品，智能设备控。
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: 梁聪落
    position: 前端工程师
    text: 精通HTML5、CSS3、Javascript，对Bootstrap， framework7， ionic等框架有着实践性项目操作，同时对目前流行的angular.js，nodejs等技术有着自己的见解。
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# 客户信息
clients:
  - name: 南方电网
    img: client01.png
  - name: 中国移动
    img: client02.png
  - name: 老黑互动
    img: client03.png
  - name: 耕天下
    img: client04.png
    

about: "一家致力于为客户提供专业网页、网站等web应用设计、移动app应用设计、交互设计、创意设计、网站seo优化、网站运维管理等服务及具有创意性的互联网团队。"

 
testimonial:
    message: "这是一个专注于web、app开发设计的具有创意性互联网团队，很看重他们对设计、技术的实力与理解。"
    author: 王新宇
    position: gengtx.com